In [2]:
import pandas as pd

In [ ]:
data= pd.read_csv(r"..\Data\Palmyra Data\Satlink_FAD_Time_21_25.csv")
data.query("BuoyName == 'SLX+471964'")

Empty DataFrame
Columns: [Unnamed: 0, BuoyName, Timestamp, Latitude, Longitude, Speed, MinOfTimes, MaxOfTimes]
Index: []

In [43]:
csv = r"..\Data\Palmyra_Data_CSV\Other Data\210925 DR+ES Dump.csv"
data2 = pd.read_csv(csv, sep= ";", index_col=None,low_memory=False)
#data2 = data2.drop(index = 0)
data2

,Name,OwnerName,MD,StoredTime,Latitude,Longitude,Bat,Temp,Speed,Drift,...,Layer8,Layer9,Layer10,Sum,Max,Mag1,Mag2,Mag3,Mag4,Unnamed: 26
0,SLX+353523,SeaEncounter,161,2021/08/21 22:35:03,6.1899,-163.12785,100.0,25.0,1.84,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SLX+353523,SeaEncounter,168,2021/08/22 15:48:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,12.0,10.0,26.0,15.0,7.0,2.0,NaN
2,SLX+353523,SeaEncounter,168,2021/08/22 16:14:01,NaN,NaN,NaN,NaN,NaN,NaN,...,63.0,0.0,0.0,68.0,63.0,31.0,21.0,22.0,19.0,NaN
3,SLX+353523,SeaEncounter,174,2021/08/22 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,SLX+353523,SeaEncounter,174,2021/08/22 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5202,SLX+331527,CapeElizabeth,174,2021/08/22 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
5203,SLX+331527,CapeElizabeth,174,2021/08/22 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
5204,SLX+331527,CapeElizabeth,174,2021/08/22 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
5205,SLX+331527,CapeElizabeth,174,2021/08/23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
5206,SLX+331527,CapeElizabeth,174,2021/08/23 01:48:00,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [39]:
print(data2["Timestamp"][9])
data2["Timestamp"] = pd.to_datetime(data2["Timestamp"], format = r'%m/%d/%y %H:%M')

12/31/24 23:18